# Generated by Django 4.2.4 on 2023-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Hemanth231#', max_length=55),
            preserve_default=False,
        ),
    ]
