# Generated by Django 4.2.4 on 2023-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
