# Generated by Django 4.2.4 on 2023-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
