# Generated by Django 4.2.4 on 2023-08-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
